version: '3'
services:
        backend:
                build: ./app
                ports:
                        - "8123:8123"
                depends_on:
                        - db
                environment:
                        - DATABASE_HOST=db
        db:
                build: ./db
